<?php

namespace AppBundle\Repository;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findLastOne(){
        $qb = $this->createQueryBuilder('c');
        $qb->select('c')
            ->setMaxResults( 1 )
            ->orderBy("c.id", 'DESC');
        $q = $qb->getQuery();

        return $q->getSingleResult();
    }

    public function addOne($currency)
    {
        $response = $this->getEntityManager()->persist($currency);
        $this->getEntityManager()->flush();

        dump($response); die;
    }
}
