<?php

namespace AppBundle\Repository;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findLastOne(){
        $qb = $this->createQueryBuilder('c');
        $qb->select('c')
            ->orderBy("c.id", 'DESC');
        $q = $qb->getQuery();

        return $q->getOneOrNullResult();
    }
}
