<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends EntityRepository
{

    /**
     * @return array
     */
    public function findAll(){
        $qb = $this->createQueryBuilder('p');
        $qb->select('p');
        $q = $qb->getQuery();

        return $q->getResult();
    }

}
